[package]
name = "regex"
version = "0.1.0"
authors = ["koosha hosseiny <i@koosha.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
